ALTER TABLE ftp_scan_runs
ADD COLUMN IF NOT EXISTS total_stations integer NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS survey_found integer NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS word_found integer NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS visio_found integer NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS pdf_found integer NOT NULL DEFAULT 0;